# Generated by Django 3.0.7 on 2020-06-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="monthyearscheddule", options={"verbose_name": "Mont Year Scheddule"},
        ),
        migrations.RemoveField(model_name="registration", name="month_year",),
        migrations.RemoveField(model_name="registration", name="training_type",),
    ]
