# Generated by Django 3.0.7 on 2020-06-08 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_auto_20200608_1946"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="month_year",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.MonthYearScheddule",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registration",
            name="training_category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.TrainingCategory",
            ),
            preserve_default=False,
        ),
    ]
