# Generated by Django 3.0.7 on 2020-06-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_auto_20200608_2311"),
    ]

    operations = [
        migrations.RemoveField(model_name="scheddule", name="end_date",),
        migrations.RemoveField(model_name="scheddule", name="start_date",),
        migrations.AddField(
            model_name="scheddule",
            name="date",
            field=models.CharField(default="Weekend", max_length=100),
            preserve_default=False,
        ),
    ]
