# Generated by Django 3.0.7 on 2020-06-08 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_auto_20200609_0452"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthYearDayScheddule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Januari"),
                            (2, "Februari"),
                            (3, "Maret"),
                            (4, "April"),
                            (5, "Mei"),
                            (6, "Juni"),
                            (7, "Juli"),
                            (8, "Agustus"),
                            (9, "September"),
                            (10, "Oktober"),
                            (11, "November"),
                            (12, "Desember"),
                        ]
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("date", models.CharField(max_length=100)),
            ],
            options={"verbose_name": "Mont Year Scheddule",},
        ),
        migrations.RemoveField(model_name="scheddule", name="date",),
        migrations.AlterField(
            model_name="registration",
            name="month_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="course.MonthYearDayScheddule",
            ),
        ),
        migrations.AlterField(
            model_name="scheddule",
            name="month_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="course.MonthYearDayScheddule",
            ),
        ),
        migrations.DeleteModel(name="MonthYearScheddule",),
    ]
