# Generated by Django 3.0.7 on 2020-06-08 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_auto_20200609_0526"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dayscheddule", options={"verbose_name": "Day Scheddule"},
        ),
        migrations.AlterModelOptions(
            name="trainingcategory",
            options={
                "verbose_name": "Training Category",
                "verbose_name_plural": "Training Categories",
            },
        ),
    ]
