# Generated by Django 3.0.7 on 2020-06-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_auto_20200609_0539"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentconfirm",
            name="proof_of_payment",
            field=models.FileField(upload_to="bukti_pembayaran/"),
        ),
        migrations.AlterUniqueTogether(name="registration", unique_together=set(),),
    ]
