# Generated by Django 3.0.7 on 2020-06-09 00:12

import course.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0008_auto_20200609_0626"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentconfirm",
            name="proof_of_payment",
            field=models.ImageField(upload_to=course.utils.upload_bukti_pembayaran),
        ),
    ]
