# Generated by Django 3.0.7 on 2020-06-09 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0009_auto_20200609_0712"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="training_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Training Offline"),
                    (1, "Training Online"),
                    (2, "Bootcamp"),
                    (3, "Premium Webinar"),
                    (4, "Free Webinar"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="registration",
            unique_together={("user", "training", "training_type")},
        ),
    ]
