# Generated by Django 3.0.7 on 2020-06-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0010_auto_20200609_1624"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Not Paid"),
                    (1, "Wait for Confirm"),
                    (2, "Paid DP"),
                    (3, "Paid Lunas"),
                ],
                default=0,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scheddule",
            unique_together={("training", "training_type", "month_year", "day")},
        ),
    ]
