# Generated by Django 3.0.7 on 2020-06-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0011_auto_20200610_0558"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentconfirm",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Not Paid"),
                    (1, "Wait for Confirm"),
                    (2, "Paid DP"),
                    (3, "Paid Lunas"),
                ],
                default=0,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="training", unique_together={("category", "name", "duration")},
        ),
    ]
