# Generated by Django 3.0.7 on 2020-06-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0013_auto_20200610_1747"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training", name="price", field=models.PositiveIntegerField(),
        ),
    ]
