# Generated by Django 3.0.7 on 2020-06-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0014_auto_20200610_1747"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("persen", models.PositiveIntegerField()),
                ("kode", models.CharField(max_length=100)),
                ("khusus_alumni", models.BooleanField(default=False)),
            ],
            options={"abstract": False,},
        ),
    ]
