# Generated by Django 3.0.7 on 2020-06-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0016_discount_end_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="discount", name="khusus_alumni",),
        migrations.AddField(
            model_name="discount",
            name="training_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Training Offline"),
                    (1, "Training Online"),
                    (2, "Bootcamp"),
                    (3, "Premium Webinar"),
                    (4, "Free Webinar"),
                ],
                default=0,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registration",
            name="diskon_kode",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
