# Generated by Django 3.0.7 on 2020-06-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0018_auto_20200611_1052"),
    ]

    operations = [
        migrations.CreateModel(
            name="JadwalFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="jadwal_file")),
            ],
            options={"abstract": False,},
        ),
    ]
