# Generated by Django 3.0.7 on 2020-06-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0019_jadwalfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaxPeserta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("max_peserta", models.PositiveIntegerField()),
            ],
            options={"abstract": False,},
        ),
    ]
