# Generated by Django 3.0.7 on 2020-06-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0020_maxpeserta"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="is_undangan_sent",
            field=models.BooleanField(default=False),
        ),
    ]
