# Generated by Django 3.0.7 on 2020-06-22 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0021_registration_is_undangan_sent"),
    ]

    operations = [
        migrations.RemoveField(model_name="registration", name="is_undangan_sent",),
    ]
