# Generated by Django 3.0.7 on 2020-06-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0022_remove_registration_is_undangan_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="fu_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="registration",
            name="last_fu",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
