# Generated by Django 3.0.7 on 2020-06-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0022_remove_registration_is_undangan_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="affiliate_kode",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
