# Generated by Django 3.0.7 on 2020-06-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0023_registration_affiliate_kode"),
        ("course", "0023_auto_20200623_1702"),
    ]

    operations = []
