# Generated by Django 3.0.7 on 2020-06-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0024_merge_20200624_2022"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="affiliate_point_used",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
