# Generated by Django 3.0.7 on 2020-06-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0025_registration_affiliate_point_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="harga_diskon",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
