# Generated by Django 3.0.7 on 2020-08-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0031_auto_20200804_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='training_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Training Offline'), (1, 'Training Online'), (2, 'Bootcamp'), (3, 'Premium Webinar'), (4, 'Free Webinar')], default=0),
            preserve_default=False,
        ),
    ]
