# Generated by Django 3.0.7 on 2020-08-31 03:46

import course.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0035_auto_20200831_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentconfirm',
            name='proof_of_payment',
            field=models.ImageField(blank=True, null=True, upload_to=course.utils.upload_bukti_pembayaran),
        ),
    ]
