# Generated by Django 3.0.7 on 2020-07-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interaksi",
            options={"verbose_name": "Interaksi", "verbose_name_plural": "Interaksi"},
        ),
        migrations.AlterField(
            model_name="interaksi",
            name="email",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="interaksi",
            name="fb",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="interaksi",
            name="ig",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="interaksi",
            name="nama_client",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="interaksi",
            name="no_hp",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="interaksi",
            name="sumber",
            field=models.CharField(
                choices=[
                    ("WA", "WA"),
                    ("TELFON", "TELFON"),
                    ("EMAIL", "EMAIL"),
                    ("Tatap Muka", "Tatap Muka"),
                    ("FB", "FB"),
                    ("IG", "IG"),
                ],
                max_length=200,
            ),
        ),
    ]
