# Generated by Django 3.0.7 on 2020-07-09 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0028_pointhistory_user"),
        ("marketing", "0002_auto_20200709_1128"),
    ]

    operations = [
        migrations.AddField(
            model_name="interaksi",
            name="training_terkait",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.Training",
            ),
        ),
    ]
