# Generated by Django 3.0.7 on 2020-07-09 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0029_auto_20200709_1652"),
        ("marketing", "0003_interaksi_training_terkait"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interaksi",
            name="training_terkait",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.Training",
            ),
        ),
    ]
