# Generated by Django 3.0.7 on 2020-07-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0004_auto_20200709_1652"),
    ]

    operations = [
        migrations.AddField(
            model_name="interaksi",
            name="date_created",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="interaksi",
            name="email",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="interaksi",
            name="fb",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="interaksi",
            name="ig",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="interaksi",
            name="nama_client",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="interaksi",
            name="no_hp",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="interaksi",
            unique_together={
                ("email", "date_created"),
                ("no_hp", "date_created"),
                ("ig", "date_created"),
                ("fb", "date_created"),
            },
        ),
    ]
