# Generated by Django 3.0.7 on 2020-07-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0005_auto_20200715_1120"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="interaksi", unique_together=set(),),
        migrations.AddConstraint(
            model_name="interaksi",
            constraint=models.UniqueConstraint(
                fields=("no_hp", "date_created"), name="no_hp unik"
            ),
        ),
    ]
