# Generated by Django 3.0.7 on 2020-07-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0006_auto_20200715_1128"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="interaksi",
            constraint=models.UniqueConstraint(
                fields=("email", "date_created"), name="email unik"
            ),
        ),
        migrations.AddConstraint(
            model_name="interaksi",
            constraint=models.UniqueConstraint(
                fields=("fb", "date_created"), name="fb unik"
            ),
        ),
        migrations.AddConstraint(
            model_name="interaksi",
            constraint=models.UniqueConstraint(
                fields=("ig", "date_created"), name="ig unik"
            ),
        ),
    ]
