# Generated by Django 3.0.7 on 2020-07-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0007_auto_20200715_1142"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="interaksi", name="no_hp unik",),
        migrations.RemoveConstraint(model_name="interaksi", name="email unik",),
        migrations.RemoveConstraint(model_name="interaksi", name="fb unik",),
        migrations.RemoveConstraint(model_name="interaksi", name="ig unik",),
        migrations.AlterField(
            model_name="interaksi",
            name="date_created",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name="interaksi",
            unique_together={
                ("email", "date_created"),
                ("fb", "date_created"),
                ("no_hp", "date_created"),
                ("ig", "date_created"),
            },
        ),
    ]
