# Generated by Django 3.0.7 on 2020-06-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="jabatan",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="mengetahui_idn_dari",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Facebook", "Facebook"),
                    ("Instagram", "Instagram"),
                    ("Telegram", "Telegram"),
                    ("Google", "Google"),
                    ("Teman", "Teman"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="ttl",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
