# Generated by Django 3.0.7 on 2020-06-18 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20200618_0806"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="facebook",),
    ]
