# Generated by Django 3.0.7 on 2020-06-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_profile_facebook"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="affiliate_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="affiliate_point",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
