# Generated by Django 3.0.7 on 2020-06-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20200622_1141"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="affiliate_point",
            field=models.IntegerField(default=0),
        ),
    ]
