# Generated by Django 3.0.7 on 2020-06-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20200622_1153"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="ukuran_kaos",
            field=models.CharField(
                blank=True,
                choices=[("L", "L"), ("XL", "XL"), ("XXL", "XXL"), ("XXXL", "XXXL")],
                max_length=10,
                null=True,
            ),
        ),
    ]
