# Generated by Django 3.0.7 on 2020-06-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_auto_20200608_1059"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
