# Generated by Django 3.0.7 on 2020-06-18 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_auto_20200618_0652"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hiidn",
            options={"verbose_name": "HI IDN", "verbose_name_plural": "HI IDN"},
        ),
    ]
