from django.urls import path
from course.views import (
    daftar_training,
    delete_registration,
    edit_pendaftaran,
    payment_confirm,
    list_jadwal,
    jadwal_upload,
    AddJadwal,
    UpdateJadwal,
    delete_jadwal,
    list_training,
    add_training,
    UpdateTraining,
    delete_training,
    list_pembayaran,
    list_pembayaran_dp_lunas,
    list_pembayaran_ditolak,
    konfirmasi_pembayaran_dp,
    konfirmasi_pembayaran_lunas,
    hapus_konfirmasi,
    tolak_pembayaran,
    list_pendaftar_belum_bayar,
    export_pendaftar_belum_bayar,
)

app_name = "course"

urlpatterns = [
    path("register/", daftar_training, name="daftar_training"),
    path("register/update/<int:pk>/", edit_pendaftaran, name="edit_pendaftaran"),
    path("register/delete/<int:pk>/", delete_registration, name="delete_registration"),
    path(
        "payment_confirm/<int:registration_id>/",
        payment_confirm,
        name="payment_confirm",
    ),
    path("list_jadwal/", list_jadwal, name="list_jadwal"),
    path("upload_jadwal/", jadwal_upload, name="upload_jadwal"),
    path("add_jadwal/", AddJadwal.as_view(), name="add_jadwal"),
    path("update_jadwal/<int:pk>/", UpdateJadwal.as_view(), name="update_jadwal"),
    path("delete_jadwal/<int:pk>/", delete_jadwal, name="delete_jadwal"),
    path("list_training/", list_training, name="list_training"),
    path("add_training/", add_training, name="add_training"),
    path("update_training/<int:pk>/", UpdateTraining.as_view(), name="update_training"),
    path("delete_training/<int:pk>/", delete_training, name="delete_training"),
    path("list_pembayaran/", list_pembayaran, name="list_pembayaran"),
    path(
        "list_pembayaran_dp_lunas/",
        list_pembayaran_dp_lunas,
        name="list_pembayaran_dp_lunas",
    ),
    path(
        "list_pembayaran_ditolak/",
        list_pembayaran_ditolak,
        name="list_pembayaran_ditolak",
    ),
    path(
        "konfirmasi_pembayaran_dp/<int:pk>/",
        konfirmasi_pembayaran_dp,
        name="konfirmasi_pembayaran_dp",
    ),
    path(
        "konfirmasi_pembayaran_lunas/<int:pk>/",
        konfirmasi_pembayaran_lunas,
        name="konfirmasi_pembayaran_lunas",
    ),
    path("hapus_konfirmasi/<int:pk>/", hapus_konfirmasi, name="hapus_konfirmasi"),
    path("tolak_pembayaran/<int:pk>/", tolak_pembayaran, name="tolak_pembayaran"),
    path(
        "list_pendaftar_belum_bayar/",
        list_pendaftar_belum_bayar,
        name="list_pendaftar_belum_bayar",
    ),
    path(
        "export_pendaftar_belum_bayar/",
        export_pendaftar_belum_bayar,
        name="export_pendaftar_belum_bayar",
    ),
]
